# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "RECOMB Conference Series"
email: "recomb-conference@gmail.com"
description: "RECOMB: Conference on Research in Computational Molecular Biology"
baseurl: ""
url: "https://recomb.org"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "G-E769F4DJMN"
googleAnalyticsSiteUrl: "recomb.org"
siteVerification: ""

# Organizer Info
organizerName: "RECOMB Conference Series"
organizerAlternateName: "RECOMB"
organizerDescription: "A series of conferences in computational molecular biology"
organizerEmail: "recomb-conference@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.recomb.org"

# Head
metaKeywords: "recomb, algorithm"
twitterAccount: "@recombconf"
# socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/team/", text: "Steering Committee"}
 - {permalink: "/satellites/", text: "Satellites"}
 - {permalink: "/history/", text: "History"}
 - {permalink: "/awards/", text: "Awards"}
 - {permalink: "https://sites.google.com/view/recombconferences", text: "Photo Albums"}
bottomNavigationLinks:
# - {link: "https://bit.ly/dfua-c4p", text: "Submit a paper"}
rightNavigationButtons:
# - {link: "https://bit.ly/dfua-c4p", text: "Submit a paper"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "RECOMB Conference Series"
heroSubTitle: "Research in Computational Molecular Biology"
#eventDate: "April 29 - May 2, 2024"
#eventLocation: "Boston, MA, United States"
#typeoutTextValues: '"2024"'
#typeoutFallback: "2024"
heroButtons:
 - {link: "https://recomb.org/recomb2024", text: "Next Conference: RECOMB 2024 in Boston"}

# About Block
aboutTitle: "About RECOMB"
# aboutBlock:
# - {title: "RECOMB", image: "conference.jpg", text: "RECOMB" }
# - {title: "Workshops", image: "workshop.jpg", text: "" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"


# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "RECOMB2024"
twitterFeed: " https://twitter.com/RECOMBconf"



# Footer
socialLinks:
 - {link: "https://twitter.com/RECOMBconf", icon: "twitter"}
 - {link: "https://www.youtube.com/@recombconf", icon: "youtube"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  links:
   - {link: "https://recomb.org/recomb2024", text: "RECOMB 2024"}
 -
  # title: "Contacts"
  # links:
  # - {link: "mailto:recomb-conference@gmail.com", text: "recomb-conference@gmail.com"}
 -
  title: "Policies"
  links:
   - {permalink: "/coi/", text: "Conflict-of-interest Policy"}




